apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook
webhooks:
- name: sidecar-injector.default.svc
  clientConfig:
    service:
      name: sidecar-injector-webhook
      namespace: default
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVQ1BINngvN0lCbFRVdFkrZnZKb1hGdUZLblc0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tjMmxrWldOaGNpMXBibXBsWTNSdmNpMTNaV0pvYjI5ckxtUmxabUYxYkhRdQpjM1pqTUI0WERUSTFNVEl5TVRFek5EY3dPVm9YRFRJMk1USXlNVEV6TkRjd09Wb3dMekV0TUNzR0ExVUVBd3drCmMybGtaV05oY2kxcGJtcGxZM1J2Y2kxM1pXSm9iMjlyTG1SbFptRjFiSFF1YzNaak1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTBSNHcvQ0VONFpPWlhMMmYzTFlzVi8yaUhHRnBxYUlEMWoyNgpKd0VYVVlrMHBZQ25OSUNwcUMzMisza29vV28xT3pLQXlOWXFpRkthUW9BcXBDZUQ2Q2FpUUlvcFNyeTgyTUlJCmxYUEs5VWFLRzUvTDMwNHZ0T0xmNzlJU0MxTVdrZGxvMGl6Z1hjY0VHOHpkdEZzYkJLTmxNUi9ENyt3a1VPbDIKc1N5MjdqQlFUdVF5dHpyZFZndE94c3BvbGl6ZlM2cXFqUFc0NmZhM0cyd2t3T1I2RGpkR2lzcHFNRGlrUlRBbQpERWpsNUE4VHFLNGFlZVJEdHRWVzBDbGhYZ3lTT1U4VkVwYWpWVVQzM25YaXpqdVFPeDQzcU92dmdNeWJaWnFmCnF6N0UvYzA0OWFGODF3YmZWNENPT3VNaUtZUE9BNFVWeU1zdG0rdEZFSmpQVkZzR2V3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVRzI3RUZ6VVBpTThtU21RTTkxRWdnKzhQZzgwd0h3WURWUjBqQkJnd0ZvQVVHMjdFRnpVUAppTThtU21RTTkxRWdnKzhQZzgwd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFpTXBveHZDSzNHcWlEM3FFQk54SE1VWloyTnQwbVpwYTZBYkZ1OC9TanFRMlJ6Zll2d0l0eElkYldqRVEKUVg1cEQrSHdac2J4NXR5a3Vja0gxV2wxTTRTeGF1cUMrd3NLcmtDcjZ2VUVyRmkweHRXUktmQjQvcjNuTG9JVgpQaVJYZEVFd3FYUUF0QVp1WElWRXBvTUdHV3FYQXkvWE9oOW5vWksvejBSRmNNTFNLMVJsWWR5S2Z6OGs5K1NwCnZqNHNPS0c4Y1IyVUowTUFlRXRGaDg4S2NyT3dKZFA3M09EOVhsejFic0dnUmdYV1pkeGpIWDVscTZXMFJuM2sKSVJrVFc4SnJQZFhkNXVMZDZjMmVTL01KdFlGcFFTMjNnL3ZZQ20zR1lXbjVOWlRMamZaVUVNV2QweUlQTUlhMApuUlE4U3l4TXhYNzdqUFJtdTNCKzZLaGFIUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 10
  failurePolicy: Ignore
